tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask_args "no-quarantine": true
cask "adoptopenjdk"
cask "osxfuse"
brew "sqlite"
brew "ansible"
brew "arping"
brew "atomicparsley"
brew "azure-cli"
brew "base64"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bcrypt"
brew "coreutils"
brew "cowsay"
brew "csshx"
brew "curl"
brew "dialog"
brew "dosbox"
brew "exif"
brew "exiftool"
brew "rtmpdump"
brew "ffmpeg"
brew "findutils"
brew "fping"
brew "git"
brew "git-cola"
brew "gnu-barcode"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "gnuplot"
brew "go"
brew "grep"
brew "grsync"
brew "htop"
brew "httperf"
brew "httpie"
brew "httrack"
brew "iperf"
brew "iperf3"
brew "jq"
brew "jsonpp"
brew "keychain"
brew "kubernetes-cli"
brew "lazygit"
brew "lcdf-typetools"
brew "lft"
brew "lftp"
brew "links"
brew "lolcat"
brew "lsof"
brew "lynx"
brew "mas"
brew "memtester"
brew "midnight-commander"
brew "minikube"
brew "mmv"
brew "moreutils"
brew "mosh"
brew "mtools"
brew "mtr"
brew "multitail"
brew "mycli"
brew "mydumper"
brew "mytop"
brew "ncdu"
brew "ncftp"
brew "netcat"
brew "ngrep"
brew "nmap"
brew "nuttcp"
brew "openshift-cli"
brew "p7zip"
brew "pdftohtml"
brew "pidof"
brew "pigz"
brew "pinentry-mac"
brew "pv"
brew "pwgen"
brew "qpdf"
brew "qprint"
brew "qrencode"
brew "rclone"
brew "rdiff-backup"
brew "ren"
brew "rename"
brew "rsnapshot"
brew "rsync"
brew "screen"
brew "shellcheck"
brew "sipcalc"
brew "speedtest-cli"
brew "ssh-copy-id", link: true
brew "sshfs"
brew "ssldump"
brew "sslscan"
brew "sysdig"
brew "tcpdump"
brew "tcpflow"
brew "tcping"
brew "tcpstat"
brew "tcptrace"
brew "tcptraceroute"
brew "telnet"
brew "tinc"
brew "tmux"
brew "trash"
brew "tree"
brew "unrar"
brew "unrtf"
brew "vagrant-completion"
brew "vim"
brew "webkit2png"
brew "wget"
brew "whois"
brew "wifi-password"
brew "wput"
brew "xhyve"
brew "youtube-dl"
cask "1password"
cask "balenaetcher"
cask "bbedit"
cask "dbeaver-community"
cask "docker"
cask "dropbox"
cask "dosbox"
cask "firefox"
cask "font-bahnschrift"
cask "font-roboto"
cask "font-roboto-mono"
cask "google-chrome"
cask "handbrake"
cask "hazel"
cask "iterm2"
cask "jdownloader"
cask "keepassx"
cask "little-snitch"
cask "macpass"
cask "megacmd"
cask "microsoft-teams"
cask "minishift"
#cask "nextcloud"
cask "microsoft-office"
cask "platypus"
cask "podman"
cask "rambox"
cask "royal-tsx"
cask "sequel-pro"
cask "skype-for-business"
cask "slack"
cask "spotify"
cask "synology-drive"
cask "tunnelblick"
cask "unetbootin"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vlc"
cask "vmware-fusion"
cask "vscodium"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Affinity Publisher", id: 881418622
mas "Apple Configurator 2", id: 1037126344
mas "Bear", id: 1091189122
#mas "BwanaDik", id: 876923947
mas "DaisyDisk", id: 411643860
mas "ForkLift", id: 412448059
mas "FruitJuice", id: 671736912
mas "Grand Theft Auto Vice City", id: 424719511
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "LanScan", id: 472226235
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "PDFScanner", id: 410968114
mas "Playgrounds", id: 1496833156
mas "Proxie", id: 897814548
mas "Reeder", id: 880001334
mas "Sid Meier's Railroads!", id: 536502825
mas "SQLPro for SQLite", id: 586001240
mas "Todoist", id: 585829637
mas "VMware Remote Console", id: 1230249825
mas "Trello", id: 1278508951
